name: Build and Upload ISO

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Pull Builder Image
        run: docker pull toaruos/build-tools:1.99.x

      - name: Build ToaruOS
        run: docker run -v ${GITHUB_WORKSPACE}:/root/misaka -w /root/misaka -e LANG=C.UTF-8 -t toaruos/build-tools:1.99.x util/build-in-docker.sh

      - name: Find and Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: toaruos.iso
          path: "*.iso"
